import Foundation

/// The engine's on-disk state, and the code that writes it.
///
/// Everything lives under one directory named for the app rather than for
/// owntone, because from the user's side there is no owntone: there is a
/// menu bar app that plays to speakers. `macos/Helper/main.swift` computes
/// these same paths from the bundle it is running inside, so neither side
/// may hardcode the app name or they will drift apart.
struct EngineInstallation {
    let root: URL

    init(root: URL = Branding.supportDirectory) {
        self.root = root
    }

    /// Parsed by owntone at launch, named by the helper's `-c`.
    var configFile: URL { root.appending(path: "owntone.conf") }

    /// Read by the helper to build librespot's argv. Kept separate from
    /// owntone.conf so editing the Spotify name never risks a malformed
    /// engine config.
    var settingsFile: URL { root.appending(path: "engine.json") }

    /// owntone's media library. Its only member is the named pipe librespot
    /// writes into; `pipe_autostart` is what turns bytes arriving there into
    /// playback.
    var libraryDirectory: URL { root.appending(path: "Library", directoryHint: .isDirectory) }

    var cacheDirectory: URL { root.appending(path: "Cache", directoryHint: .isDirectory) }
    var logDirectory: URL { root.appending(path: "Logs", directoryHint: .isDirectory) }

    var databaseFile: URL { root.appending(path: "songs3.db") }
    var audioPipe: URL { libraryDirectory.appending(path: "spotify.fifo") }

    /// owntone's own log. The helper separately captures the process's
    /// stdout and stderr to Logs/owntone.log, which is where a failure too
    /// early to have read this config shows up.
    var serverLogFile: URL { logDirectory.appending(path: "owntone-server.log") }

    // MARK: - Writing

    /// Creates the directory tree, the named pipe and both config files.
    ///
    /// Returns true when something the engine reads at launch actually
    /// changed, which is the caller's signal to restart the agents. Writing
    /// identical bytes returns false, so an app launch that changes nothing
    /// does not interrupt playback.
    @discardableResult
    func prepare(connectName: String, showsInSpotify: Bool) throws -> Bool {
        let manager = FileManager.default
        for directory in [root, libraryDirectory, cacheDirectory, logDirectory] {
            try manager.createDirectory(at: directory, withIntermediateDirectories: true)
        }

        try createAudioPipeIfNeeded()

        let configChanged = try write(owntoneConfig(), to: configFile)
        let settingsChanged = try write(
            settingsJSON(connectName: connectName, showsInSpotify: showsInSpotify),
            to: settingsFile
        )
        return configChanged || settingsChanged
    }

    /// A named pipe, not a regular file. owntone identifies it by its file
    /// type, so an ordinary empty file here would be scanned as a broken
    /// track instead.
    private func createAudioPipeIfNeeded() throws {
        var status = stat()
        if lstat(audioPipe.path, &status) == 0 {
            if status.st_mode & S_IFMT == S_IFIFO { return }
            // Something else is squatting on the path. Move it aside rather
            // than delete it: if this is the user's file, losing it silently
            // would be worse than an extra file on disk.
            let aside = audioPipe.appendingPathExtension("displaced")
            try? FileManager.default.removeItem(at: aside)
            try FileManager.default.moveItem(at: audioPipe, to: aside)
        }

        guard mkfifo(audioPipe.path, 0o600) == 0 else {
            throw EngineInstallationError.pipeCreationFailed(
                audioPipe.path, String(cString: strerror(errno))
            )
        }
    }

    /// Writes only when the bytes differ, and via a temporary file so a
    /// crash mid-write cannot leave the engine a truncated config.
    private func write(_ contents: String, to url: URL) throws -> Bool {
        let data = Data(contents.utf8)
        if let existing = try? Data(contentsOf: url), existing == data { return false }

        let temporary = url.deletingLastPathComponent()
            .appending(path: ".\(url.lastPathComponent).new")
        try data.write(to: temporary, options: .atomic)
        _ = try FileManager.default.replaceItemAt(url, withItemAt: temporary)
        return true
    }

    // MARK: - Contents

    private func owntoneConfig() -> String {
        // trusted_networks is localhost only, deliberately. owntone's HTTP
        // interface is an unauthenticated control API for every speaker in
        // the house; the spike widened it to the LAN to reach the web UI
        // from a phone, and nothing here needs that. This app talks to
        // 127.0.0.1 and the phone talks to librespot.
        """
        # Generated by \(Branding.appName). Edits are overwritten on launch.

        general {
        \tuid = "\(escaped(NSUserName()))"
        \tdb_path = "\(escaped(databaseFile.path))"
        \tlogfile = "\(escaped(serverLogFile.path))"
        \tloglevel = log
        \tcache_dir = "\(escaped(cacheDirectory.path))"
        \ttrusted_networks = { "localhost" }
        \tipv6 = no
        }

        library {
        \tname = "\(escaped(Branding.appName))"
        \tdirectories = { "\(escaped(libraryDirectory.path))" }
        \tpipe_autostart = true
        }

        """
    }

    private func settingsJSON(connectName: String, showsInSpotify: Bool) -> String {
        // Hand-rolled rather than JSONEncoder so the file stays readable
        // and stably ordered: it is diffed against what is already on disk
        // to decide whether the agents need restarting.
        //
        // The app's own build is in here for that diff and nothing else. The
        // agents run the helper out of the bundle, and launchd keeps a running
        // job on the old binary until something stops it -- so an update
        // that changed only the helper would otherwise never take effect.
        """
        {
          "app": \(quotedJSON(Branding.build)),
          "connectName": \(quotedJSON(connectName)),
          "deviceType": \(quotedJSON(SpotifyDeviceType.advertised.rawValue)),
          "showsInSpotify": \(showsInSpotify),
          "audioPipe": \(quotedJSON(audioPipe.path)),
          "bitrate": 320
        }

        """
    }

    /// libconfuse strings are double-quoted with backslash escapes.
    private func escaped(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }

    private func quotedJSON(_ value: String) -> String {
        // Without .withoutEscapingSlashes every path in the file comes out as
        // \/Users\/... -- valid JSON, unreadable to a human opening it.
        let data = try? JSONSerialization.data(
            withJSONObject: [value], options: [.withoutEscapingSlashes]
        )
        guard
            let data,
            let array = String(data: data, encoding: .utf8),
            array.count > 2
        else {
            return "\"\""
        }
        return String(array.dropFirst().dropLast())
    }
}

enum EngineInstallationError: LocalizedError {
    case pipeCreationFailed(String, String)

    var errorDescription: String? {
        switch self {
        case .pipeCreationFailed(let path, let reason):
            return "Could not create the audio pipe at \(path): \(reason)"
        }
    }
}
