import Foundation

/// Where the bundled engine listens. The ports are the engine's defaults; the
/// websocket port is also discoverable at runtime via `GET /api/config`, which
/// we should start doing once the config file is generated by this app.
struct EngineEndpoint: Sendable, Hashable {
    var host: String = "127.0.0.1"
    var apiPort: Int = 3689
    var notifyPort: Int = 3688

    static let `default` = EngineEndpoint()

    var apiBase: URL {
        URL(string: "http://\(host):\(apiPort)")!
    }

    var notifyURL: URL {
        URL(string: "ws://\(host):\(notifyPort)/")!
    }

    func api(_ path: String) -> URL {
        apiBase.appending(path: path)
    }
}
